//================================================================
//  PROGRAMMER : ¤û³Ó¹l
//  DATE       : 2016-10-3
//  FILENAME   : HW01AB01B02024.CPP 
//  DESCRIPTION   : This is a program that output a text drawing of an elk.
//================================================================

#include "stdafx.h"
#include <iostream>
using namespace std;


int main()
{
	cout << "/  \\         /    \\" << endl;
	cout << "\\_  \\       /    _/" << endl;
	cout << "_\\   \\    /    /__" << endl;
	cout << "\\___  \\__/  __/ " << endl;
	cout << "    \\_        -/ " << endl;
	cout << "       | @  @   \\_  " << endl;
	cout << "       |              "            << endl;
	cout << "     -//     /\\       " << endl;
	cout << "      /o)  (o/\\ \\_ " << endl;
	cout << "     /______/ /  " << endl;
	cout << "       \\___/ " << endl;

	//Use cout function and endl to output an elk graph and shift lines 
	return 0;
}

